### ISSUE TITLE
[Feature Request] show remote endpoint for each connection on the server.

### ISSUE THREAD

**Issue by patsevanton** [jwkohnen/conntrack-stats-exporter#23]
Hello! Thanks for conntrack-stats-exporter.

For example:
```
# HELP conntrack_open_connections How many open connections are there to the remote host
# TYPE conntrack_open_connections gauge
conntrack_open_connections{host="10.0.1.5:3306"} 49
conntrack_open_connections{host="10.0.1.12:8080"} 19
```

**Comment by fdomain** [comment]
The cardinality of generating such metric per host could become significant for host communicating with a lot of remote hosts. Just out of curiosity, what is your use case ?

IMO, it's a bit out of the scope of this exporter.
`conntrack-stats-exporter` parses statistics reported by nf_conntrack with `conntrack -S` command (it simply reads from `/proc/net/stat/nf_conntrack`).
Getting stats per host would require to parse `conntrack -L` output, which could be cumbersome.
It this request is accepted, implementing https://github.com/jwkohnen/conntrack-stats-exporter/issues/15 first is preferable to avoid output parsing.

@jwkohnen what's your opinion on this ?

**Comment by patsevanton** [comment]
Thanks. But it is no longer relevant.

**Comment by jwkohnen** [comment]
I agree with the argument, that it would mean an unbound cardinality; such functionality would need some config mechanism to limit the cardinality somewhat and that again might be very use case dependent. 

Closing as it seems to be no more relevant anyway.
